CREATE TYPE user_role AS ENUM ('admin', 'staff');
CREATE TYPE product_status AS ENUM ('active', 'archived');
CREATE TYPE product_identifier_type AS ENUM ('barcode', 'qr');
CREATE TABLE users (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role user_role NOT NULL DEFAULT 'staff', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE sessions (token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX sessions_user_idx ON sessions(user_id);
CREATE TABLE login_attempts (attempt_key TEXT PRIMARY KEY, failed_count INTEGER NOT NULL CHECK (failed_count >= 0), window_started_at TIMESTAMPTZ NOT NULL, blocked_until TIMESTAMPTZ, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX login_attempts_updated_idx ON login_attempts(updated_at);
CREATE TABLE password_reset_tokens (token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX password_reset_tokens_user_idx ON password_reset_tokens(user_id);
CREATE TABLE password_reset_attempts (attempt_key TEXT PRIMARY KEY, request_count INTEGER NOT NULL CHECK (request_count >= 0), window_started_at TIMESTAMPTZ NOT NULL, blocked_until TIMESTAMPTZ, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX password_reset_attempts_updated_idx ON password_reset_attempts(updated_at);
CREATE TABLE products (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, status product_status NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE product_variants (id BIGSERIAL PRIMARY KEY, product_id BIGINT NOT NULL REFERENCES products(id), size TEXT NOT NULL, color TEXT NOT NULL, sku TEXT UNIQUE NOT NULL, price_cents INTEGER NOT NULL CHECK (price_cents >= 0));
CREATE TABLE product_identifiers (id BIGSERIAL PRIMARY KEY, variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE, identifier_type product_identifier_type NOT NULL, code TEXT NOT NULL UNIQUE, UNIQUE (variant_id, identifier_type));
CREATE INDEX product_identifiers_variant_idx ON product_identifiers(variant_id);
CREATE TABLE inventory_levels (variant_id BIGINT PRIMARY KEY REFERENCES product_variants(id), quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0), reorder_point INTEGER NOT NULL DEFAULT 5 CHECK (reorder_point >= 5), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE sales (id BIGSERIAL PRIMARY KEY, staff_id BIGINT REFERENCES users(id), subtotal_cents INTEGER NOT NULL CHECK (subtotal_cents >= 0), discount_cents INTEGER NOT NULL DEFAULT 0 CHECK (discount_cents >= 0), total_cents INTEGER NOT NULL CHECK (total_cents >= 0), payment_method TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE payments (id BIGSERIAL PRIMARY KEY, sale_id BIGINT NOT NULL UNIQUE REFERENCES sales(id), amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0), method TEXT NOT NULL CHECK (method = 'cash'), status TEXT NOT NULL CHECK (status = 'recorded'), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE sale_items (id BIGSERIAL PRIMARY KEY, sale_id BIGINT NOT NULL REFERENCES sales(id), variant_id BIGINT NOT NULL REFERENCES product_variants(id), quantity INTEGER NOT NULL CHECK (quantity > 0), unit_price_cents INTEGER NOT NULL, discount_cents INTEGER NOT NULL DEFAULT 0, total_cents INTEGER NOT NULL, discount_reason TEXT);
CREATE TABLE sale_returns (id BIGSERIAL PRIMARY KEY, sale_id BIGINT NOT NULL REFERENCES sales(id), sale_item_id BIGINT NOT NULL REFERENCES sale_items(id), quantity INTEGER NOT NULL CHECK (quantity > 0), refund_cents INTEGER NOT NULL CHECK (refund_cents >= 0), reason TEXT NOT NULL, created_by BIGINT NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX sale_returns_item_idx ON sale_returns(sale_item_id);
CREATE TABLE inventory_movements (id BIGSERIAL PRIMARY KEY, variant_id BIGINT NOT NULL REFERENCES product_variants(id), quantity_delta INTEGER NOT NULL, reason TEXT NOT NULL, reference_type TEXT, reference_id BIGINT, created_by BIGINT REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX product_search_idx ON products USING gin (to_tsvector('simple', name));
CREATE INDEX movement_variant_idx ON inventory_movements(variant_id, created_at DESC);
